// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avatar.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvatarByID = `-- name: GetAvatarByID :one
SELECT id, name, key, is_active, sort_order, created_at, updated_at FROM avatars
WHERE id = $1
`

func (q *Queries) GetAvatarByID(ctx context.Context, id pgtype.UUID) (Avatar, error) {
	row := q.db.QueryRow(ctx, getAvatarByID, id)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAvatars = `-- name: ListActiveAvatars :many
SELECT id, name, key, is_active, sort_order, created_at, updated_at FROM avatars
WHERE is_active = true
ORDER BY sort_order
`

func (q *Queries) ListActiveAvatars(ctx context.Context) ([]Avatar, error) {
	rows, err := q.db.Query(ctx, listActiveAvatars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avatar
	for rows.Next() {
		var i Avatar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
