// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capsules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCapsule = `-- name: CreateCapsule :one
INSERT INTO capsules (user_id, message)
VALUES ($1, $2)
RETURNING id, user_id, message, drawn_at, created_at
`

type CreateCapsuleParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Message string      `json:"message"`
}

func (q *Queries) CreateCapsule(ctx context.Context, arg CreateCapsuleParams) (Capsule, error) {
	row := q.db.QueryRow(ctx, createCapsule, arg.UserID, arg.Message)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.DrawnAt,
		&i.CreatedAt,
	)
	return i, err
}

const drawCapsule = `-- name: DrawCapsule :one
UPDATE capsules
SET drawn_at = NOW()
WHERE id = (
    SELECT id FROM capsules
     WHERE drawn_at IS NULL
     ORDER BY RANDOM()
     LIMIT 1
     FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, message, drawn_at, created_at
`

func (q *Queries) DrawCapsule(ctx context.Context) (Capsule, error) {
	row := q.db.QueryRow(ctx, drawCapsule)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.DrawnAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCapsuleCount = `-- name: GetCapsuleCount :one
SELECT COUNT(*) FROM capsules
 WHERE drawn_at IS NULL
`

func (q *Queries) GetCapsuleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getCapsuleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
