// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, nickname, password_hash, avatar_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, nickname, password_hash, avatar_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Nickname     string      `json:"nickname"`
	PasswordHash string      `json:"password_hash"`
	AvatarID     pgtype.UUID `json:"avatar_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Nickname,
		arg.PasswordHash,
		arg.AvatarID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.PasswordHash,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, nickname, password_hash, avatar_id, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.PasswordHash,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, email, nickname, password_hash, avatar_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByUserID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.PasswordHash,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
   SET avatar_id   = $2,
       updated_at  = NOW()
 WHERE id = $1
RETURNING id, email, nickname, password_hash, avatar_id, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	ID       pgtype.UUID `json:"id"`
	AvatarID pgtype.UUID `json:"avatar_id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.PasswordHash,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
